apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hydra-shadow-worker
  namespace: hydra-system
spec:
  selector:
    matchLabels:
      app: hydra-worker
  template:
    metadata:
      labels:
        app: hydra-worker
    spec:
      hostIPC: true
      hostNetwork: true
      containers:
      - name: worker
        image: hydra-worker:latest
        securityContext:
          privileged: true
        resources:
          limits:
            nvidia.com/gpu: "8"
        volumeMounts:
        - name: shared-nvme
          mountPath: /mnt/nvme-of
          readOnly: true
        - name: dev-mem
          mountPath: /dev/mem
      volumes:
      - name: shared-nvme
        hostPath:
          path: /mnt/shared_nvme
          type: DirectoryOrCreate
      - name: dev-mem
        hostPath:
          path: /dev/mem
